import React from 'react'
import Seo from '../components/seo/Seo'
import Layout from '../components/Layout'
import ArticleHeader from '../components/ArticleHeader'
import occupy from '../public/occupycityhall.png'

const PartirDesRessourcesExistantes = () => {
    const titre = 'Partir des ressources existantes'
    const description = 'Traduction complète'

    return (
        <div>


    
            <Layout>


       
                <Seo title={titre} description={description} />

                    <ArticleHeader src={occupy} title={"Partir des ressources existantes "} author="MPD150" date='2017'/>

<div>

Introduction 
Dans la première partie de ce rapport, nous avons passé en revue les méthodes corrompues, brutales et l'histoire oppressante de Minneapolis Département Police. Dans la deuxième section, nous avons discuté du paysage actuel de la relation entre la communauté et la police à Minneapolis. Dans cette dernière section, nous allons présenter nos réflexions sur les façons dont nous pourrions faire en sorte que cette tragédie longue de cent cinquante ans prenne fin, pour ouvrir un nouveau chapitre dans l’histoire de Minneapolis. 
Nous avons exploré les problèmes du MPD en profondeur. La culture du MPD est celle où le racisme et la brutalité sont tacitement autorisés, et où les agents sont tenus par un lien d'honneur [are honor-bound] de couvrir la mauvaise conduite de l'autre. Les plaintes pour fautes commises par des policiers sont rejetées, dissimulées et ignorée, et même lorsqu'ils sont reconnus coupables de brutalité, la ville ne peut pas les tenir pour responsables, et beaucoup d'entre eux continuent à travailler on the force. L'indignation de la communauté conduit à des appels pour des enquêtes civiles, des formations à la diversité et les caméras corporelles – tout ce qui ne parvient pas à résoudre les problèmes sous-jacents. Pendant ce temps, le syndicat de la police a une quantité formidable de pouvoir politique, et il utilise ce pouvoir pour prévenir, limiter et détruire même les petites tentatives de rendre des comptes. 150 ans d'histoire nous montre que la réforme de la police est impossible : il est temps de rêver plus grand. Il est temps de rêver à l'abolition de la police.
Imaginez un instant qu’on vous mette en charge de la stabilité dans une ville nouvellement créée, établie dans un environnement sûr et sain. Comment allez-vous résoudre les problèmes rencontrés par vos amis et vos voisins ? Comment réagirez-vous si une crise apparaît, ou si une explosion de violence survient ? Votre premier choix sera-t-il de faire appel à une armée qui ne rend aucun compte, et qui a un lourd passif d’oppression et de violence lors de ses patrouilles incessantes dans votre quartier ?
Pour commencer à envisager un monde différent, nous devons commencer par décomposer les fonctions que la police exerce dans notre communautés. En ce moment, la police est chargée de trois grandes choses dans notre ville : ils maintiennent l'ordre, répondent aux crises et traduisent les criminels en "justice".

Maintien de l'ordre
Notre système de justice pénale repose sur l'idée que le crime est une forme de mauvaise conduite individuelle et peut être évité en mettant les "méchants" en prison. D'un autre coté, le bon sens et les recherches en sciences sociales nous disent que la plupart des crime sont causés par la pauvreté et la marginalisation, et ne peuvent être empêchés sans aborder les causes sous-jacentes. Selon les termes de Tony Bouza, chef retraité de la police de Minneapolis : « l'idée de la police comme ceux qui préviennent les crimes est une bêtise. Au moment où le flic apparaît, le criminel s'est formé [the criminal has been formed] et le crime a été commis". 
Lorsque les êtres humains vivaient dans des des communautés où la plupart des gens se connaissaient les uns les autres, le crime n'était pas aussi préoccupation qu'il l'est actuellement. De nos jours, nous vivons dans des communautés massives où quelques uns contrôlent la plupart des richesses et du pouvoir, et le reste d'entre nous doit s'en sortir sur les restes. Bien sûr qu'il y a du crime et désordre dans notre ville, étant donné notre état, notre pays, et notre monde [given our state, our country, and our world]. Mais la solution à ces crimes et à ces désordres n'est pas d'enfermer les gens - il s'agit de s'assurer qu'ils ont ce dont ils ont besoin pour s'en sortir. Comme Greg Boyle, fondateur de Homeboy Industries, une agence de sécurité communautaire à Los Angeles a dit : "rien n'arrête mieux une balle qu'un emploi". Donner à nos communautés les ressources dont elles ont besoin pour s'épanouir feront beaucoup plus pour prévenir les vols, les agressions et les meurtres que la « fermeté de la police » face au crime n'a jamais pu.
Mais arrêter la criminalité n'est même pas ce que prend le plus de temps aux agents de police - les contraventions et les arrêts de circulation prennent de loin le plus de temps pour la plupart des policiers. C'est en 2017 – il existe de bien meilleures façons de donner à quelqu'un une contravention pour excès de vitesse que d'avoir quelqu'un avec une arme à feu qui vous arrête sur l'autoroute, mettant vos deux vies en jeu. Trouvons des moyens de tenir chacun responsable quand il fait du mal avec des manières qui n'exigent pas la menace de violence.
En plus de "prévenir la criminalité", la police impose the morality of powerful sur tout le monde. Ça signifie forcer les personnes sans domicile à sortir de notre champ de vision, criminaliser les consommateurs de drogues et incarcérer des travailleuses du sexe, même quand leurs choix ne nuisent à personne. Des siècles de criminalisation n'ont pas mis fin à l'itinérance [homelessness], à la consommation de drogue ou au travail du sexe - il est temps de réexaminer notre relation avec ce que les riches et les puissants jugent "inacceptable".
Enfin, le maintien de l'ordre exige que toute contestation de l'autorité soit brutalement écrasée - c'était aussi vrai pendant la grève des camionneurs de 1934, comme ça l'a été pendant l'État libre de Minnehaha de 1999, comme à la suite du meurtre de Jamar Clark en 2015. Aussi longtemps que nous aurons une force de police militarisée prête à attaquer toute personne qui menace le statut quo, les défenseurs de la justice sociale vont souffrir de la violence, de l'emprisonnement et de la la difficulté à trouver un emploi et un logement avec un casier judiciaire. Est-ce vraiment ainsi que nous voulons que notre communauté réponde aux appels à mieux se traiter les uns les autres [to respond to calls for us to treat each other better] ?

Répondre à une crise
Lorsque quelqu'un appelle le 911, la police est presque toujours dépêchée sur place, même dans les cas qui concernent principalement les ambulanciers ou les pompiers. La police est mal formée pour faire face à la vaste la majorité des crises ; pour tous les appels dans lequel l'utilisation de la violence devient nécessaire, il y a beaucoup d'appels pour des crises de santé mentale et de violences domestiques où les flics sont mal équipés pour faire face à ces situations. La solution ne consiste pas à former les agents à tout – ce sont plutôt des réponses aux situations d'urgence plus spécialisées et décentralisées.
Le 911 n’est apparu dans le Minnesota que dans les années quatre-vingt. À l’époque, beaucoup de gens étaient sceptiques quant à l’idée de centraliser la police, le personnel paramédical et les pompiers dans le même centre d’appels, étant donné les différentes fonctions qu’ils remplissent. Mais si les répartiteurs peuvent décider lequel de ces trois services envoyer en cas d’urgence, pourquoi ne pas faire appel à plus de services ? Pourquoi ne pas avoir des professionnels de la santé mentale, des travailleurs sociaux, des spécialistes des violences conjugales, et d’autres personnels qui pourraient être envoyés sur place en fonction de la situation ? Ou, pour le dire autrement, combien d’appels au 911 nécessitent vraiment l’intervention de personnes qui portent des armes ? 

Justice pénale
Quand avez-vous entendu parler pour la dernière fois de quelqu'un dans votre vie qui signale un vol à la police ? L'auteur de l'infraction a-t-il été arrêté ? La victime a-t-elle récupéré ses biens ? Qu'en est-il de la dernière fois où vous avez entendu parler de quelqu'un qui est tenu pour responsable d'une agression sexuelle après que la victime l'ait signalé à la police ? Le fait est que que la police n'est pas très douée pour résoudre des crimes, même aussi grave qu'un meurtre. Par exemple, en 2015, le MPD n'a résolu 26 des 45 meurtres qui ont été commis. Une partie du problème est le manque de confiance dans la police - de nombreux habitants ne signalent pas les crimes in the first place, ou refusent de fournir des preuves, ceci en lien avecm avec leurs expériences passées avec la police. Pour essayer de contourner ces problèmes, le MPD investit dans des programmes visant à faire parler les témoins à la police, y compris un groupe de comnunity leaders qui fournit des conseils après les fusillades et une équipe de travailleurs sociaux du centre médical du comté de Hennepin qui essaye de décourager les représailles violentes. Mais si nous voulons être en mesure d'aborder la violence et le préjudice de manière constructive, laisser l'enquête sur les crimes entre les mains d'une agence largement discréditée overly reliant on incarceration n'est pas une option quels que soient leurs efforts de sensibilisation.
D'autres modèles peuvent nous aider à apprendre comment répondre à ce qui fait du tort, de manière à permettre for humanity and growth on the part of the victim and the perpetrator.. Cela peut inclure les méthodes traditionnelles de peace-making pratiquée par les peuples autour du globe, ainsi que des options plus immédiates : par exemple, les agences de justice réparatrices ici dans les villes jumelées pourraient être chargées de résoudre les conflits communautaires à l'extérieur
de la salle d'audience. Un autre modèle à considérer est la Comission Vérité et Réconciliation qui aida l'Afrique du Sud à commencer à guérir des blessures de l'apartheid. Une chose est certaine : nous ne pouvons pas concevoir un régime plus inhumain, raciste et préjudiciable de résoudre les conflits que le système pénal américain si nous essayons.

Investir dans un avenir meilleur
Nous pouvons vivre en sûreté et en bonne santé dans des communautés sans police ; en fait, la criminalisation et la violence que la police apporte dans nos communautés les rendent moins sûres. Ce dont nous avons besoin, ce sont des ressources - le temps et le soutien nécessaires à la création d'un réseau de fournisseurs de sécurité communautaire [community safety providers] qui ne résoudre pas tous les problèmes difficiles avec la menace de la force. Le budget proposé par le maire pour 2018 augmente le financement du département de police de Minneapolis jusqu'à 179,2 millions de dollars par an. Pensez à ce que cet argent pourrait faire s'il était utilisé pour aider les gens à sortir de la pauvreté, construire des logements abordables, ou investir dans des programmes d'emploi, d'éducation, de traitement des addictions, de services de santé mentale, et au-delà. 150 ans d'investissement dans le service de police de Minneapolis n'a certainement pas mis fin au tort [harm] dans notre ville - il est temps d'essayer quelque chose de nouveau.
Le désinvestissement ne doit pas se passer du jour au lendemain. Nous pouvons prendre notre temps pour construire les alternatives dont nous avons besoin pour assurer la sécurité de nos communautés, en sous-tirant quelques dollars à la fois hors de la police pour les placer dans d'autres options de sécurité communautaire. À l'heure actuelle, c'est le bon moment pour commencer – les policiers "Baby Boomer" prennent leur retraite en grand nombre et des services à travers l'ensemble du pays s'efforcent de les remplacer. Une voie possible de désinvestissement pourrait commencer par un gel des embauches. Pour chaque policier « Baby Boomer » qui s'en va, son salaire est transféré dans un nouveau programme de sécurité communautaire.
Ces idées ne sont pas seulement des rêves utopiques - le soutien à l'abolition de la police se développe dans tout le pays. Des militants de Chicago, New York, Durham et d'autres villes plaident en faveur de plates-formes « Beyond Policing » qui demandent aux responsables municipaux de réorienter les budgets de la police vers des initiatives de sécurité menées par la communauté. L'idée d'investir dans des alternatives à la police a déjà été testée à Minneapolis : en 2016, le conseil municipal a voté un budjet de 500 000 dollars dans des programmes de sécurité menés par la communauté dans les communautés de Broadway et de Little Earth. Mais un demi-million de dollars n'est qu'une goutte d'eau dans l'océan par rapport aux centaines de millions que nous dépensons chaque année pour la police. Si nous voulons vraiment construire un avenir plus sûr et plus humain, nous devrons rêver beaucoup plus grand.
La première étape sur la voie d'une ville sans police consiste à déterminer les besoins de nos communautés et à identifier les alternatives qui peuvent répondre à ces besoins. MPD150 ne prétend pas avoir toutes les réponses, mais nous savons que si on leur donne une chance, nos communautés seront à la hauteur pour créer un monde meilleur pour nos enfants.

Qui allez-vous appeler ? 
Nous n’avons pas les ressources nécessaires pour vivre dès maintenant dans une ville sans police, mais nous avons ce qu’il faut pour commencer. Dans les pages qui suivent, nous allons partager quelques idées sur la manière d’utiliser les programmes existants pour commencer à mettre en place un réseau de sécurité communautaire qui puisse remplacer la police.  Si l'une de ces ressources vous semble utile, vous pouvez en apprendre davantage à leur sujet, y compris les coordonnées, sur notre site web à l'adresse www.mpd150.com. Nous commencerons par examiner l'une des tâches pour lesquelles la police est la moins bien équipée : répondre aux appels lorsqu'une personne est en crise de santé mentale.

Répondre à la souffrance psychique 
Ce n’est un secret pour personne que les États-Unis ne dis­posent pas de structures de soins destinées à la santé mentale adéquates. Depuis que la plupart des hôpitaux psychiatriques n’ont plus été financés et ont été fermés dans les années soixante et soixante-dix, les personnes qui traversent des crises psychologiques n’ont guère de recours. À l’heure actuelle, lorsqu’une personne en crise appelle le 911, la police est la première à être envoyée sur place.  On estime que un appel de police sur dix concerne une personne en crise de santé mentale, mais la police est mal formée pour faire face à ces crises.
Aux États-Unis, le policier moyen reçoit cinquante-­huit heures de formation sur les armes à feu et quarante-neuf heures pour les tactiques défensives, mais seulement huit heures de formation à la désescalade, un élément clé pour aider à résoudre les crises de souffrance psychique. Cela se reflète dans le nombre de personnes atteintes de maladie mentale qui ont été brutalisées et tuées par des policiers, à Minneapolis et dans tout le pays, depuis de nombreuses années. 
Heureusement, nous disposons déjà d’un certain nombre d’alternatives à la police pour faire face aux crises liées à la santé mentale à Minneapolis. Le comté de Hennepin dispose d’un programme appelé COPE (Community Outreach for Psychiatric Services) qui envoie des intervenants qualifiés en santé mentale sur place, à toute heure du jour ou de la nuit. Il existe également un programme similaire pour répondre aux crises de souffrance psychique chez les jeunes, appelé Hennepin County Child Crisis. Nous disposons également d’un réseau d’assistances téléphoniques locales pour ces situations de souffrance psychique, comme Crisis Connection, Tubman’s Crisis Line et MN Warmline. 
La plus grande limite à laquelle sont confrontés les programmes de réponses aux crises de souffrance psychique est le manque de ressources. Si nous financions les services de soins de santé mentale à une plus grande échelle dans notre société, il n'y aurait pas autant de crises au départ. Même les programmes que nous avons sont sous-financés : Crisis Connection, qui fonctionne depuis près de cinquante ans, a failli être fermée à l'été 2017 après que les législateurs des États aient refusé de mettre de côté 1,4 million de dollars pour continuer à la financer. Le COPE ne reçoit pas non plus suffisamment d'argent - lorsque tous ses intervenants sont déjà dépêchés et qu'ils reçoivent un appel, tout ce qu'ils peuvent faire est de dire à la personne qui demande de l'aide d'appeler le service de police. Si nous voulons que notre ville s'occupe des personnes en crise de santé mentale, nous devrions faire des intervenants en santé mentale nos premiers intervenants, plutôt qu'une réflexion après coup.

Les sans-abri 
Depuis que le Minnesota a adopté sa première loi sur le vagabondage au début du XXe siècle, l’un des rôles du service de police de Minneapolis a été de rafler et de criminaliser les personnes sans domicile fixe. Cela reste vrai aujourd’hui ; Minneapolis a criminalisé toute une série d’activités qui sont inévitables pour de nombreux sans-abri, notamment la mendicité dans certains endroits, le fait de dormir dans des véhicules et l’utilisation de structures temporaires telles que des tentes. La police entre également en contact avec les sans-abri d’autres manières, notamment lorsque des habitants qui se plaignent des sans-abri appellent le 911, ou lorsque la police est chargée de « nettoyer » un quartier de la ville avant un événement majeur comme le Super Bowl. Arrêter, brutaliser et criminaliser les personnes qui n’ont pas accès à un logement stable ne les aide pas à trouver un toit ; au contraire, cela leur rend la tâche plus difficile. Nous devons trouver de meilleurs moyens de traiter nos problèmes de logements.
Certaines des ressources dont nous avons besoin pour résoudre notre crise du logement existent déjà : Minneapolis dispose d’un certain nombre de foyers et de prestataires de services sociaux qui peuvent aider les personnes sans domicile fixe à trouver un endroit où dormir, à court ou à long terme. Nous disposons d’un réseau particulièrement solide de ressources pour les jeunes sans-abri, notamment des organisations comme Streetworks, Avenues for Homeless Youth, The Bridge et Youthlink. Il existe même une équipe de maraude dirigée par l’église St. Stephens, qui cherche à être le premier point de contact pour les personnes vivant dans la rue, en les aidant à trouver des ressources et en intervenant parfois dans les interactions entre la communauté [des sans-abri] et la police qui, autrement, pourraient mener à une arrestation.
Nous sommes confrontés à une crise des logements abordables à Minneapolis. Le taux d’inoccupation des logements locatifs tourne autour de 2 % et la population augmente rapidement sans que l’on construise suffisamment de nouveaux logements. Dans le même temps, nos foyers pour sans-abri sont remplis : nous ne disposons que d’environ six cents lits pour adultes seuls dans la ville et des dizaines de personnes sont refusées chaque nuit, forcées à dormir dehors par manque de financement. Si nous voulons résoudre le problème des sans-abri à Minneapolis, nous devrions commencer par là, en augmentant le nombre de lits disponibles dans les foyers, en construisant davantage de logements abordables et en résistant à la gentrification, et non pas en envoyant la police arrêter tous les sans-abri. 

Les contrôles routiers 
Les policiers procèdent couramment à des contrôles de « personnes suspectes », de « véhicules suspects » et de « circulation ». Les personnes de couleur sont arrêtées de manière dis­pro­portionnée lors de ces contrôles sous des prétextes peu convaincants et sont parfois fouillées dans l’espoir de trouver des preuves d’activités criminelles. Un rapport de l'ACLU datant de 2015 a montré que les personnes de couleur sont beaucoup plus susceptibles d'être arrêtées pour des infractions au code de la route. Par exemple, les Noir·es ont presque neuf fois plus de chances que les Blanc·hes de finir au poste après un contrôle routier en journée. Les contrôles routiers ne sont pas seulement des désagréments mineurs ;  ils sont dangereux, tant pour les membres de la communauté que pour les agents. Philando Castile a été tué lors d’un tel contrôle après en avoir subi quarante-neuf en l’espace de treize ans. 
Les contrôles routiers n’apportent rien en tant que pratique de sécurité communautaire. Le peu de bien qu’ils font est contre­balancé par le harcèlement et la violence qu’ils infligent aux communautés marginalisées. Ceux qui enquêtent sur des personnes ou des véhicules "suspects" devraient être entièrement éliminés : personne ne devrait avoir à être harcelé ou fouillé par la police simplement à cause de son apparence. Il y a aussi de meilleures façons de traiter les infractions au code de la route : si quelqu'un a un feu arrière cassé, par exemple, un avertissement par courrier serait non seulement aussi efficace qu'un contrôle routier, mais aussi un moyen plus sûr de le faire savoir. De nombreux États le font déjà avec les infractions au péage. Même dans le cas d’infractions plus immédiates, comme les excès de vitesse ou la conduite imprudente, le fait de faire intervenir un policier armé ne fait que renforcer la probabilité que le contrôle se termine en tragédie. 
Les contrôles routiers sont une mauvaise idée et nous devrions chercher d’autres moyens d’assurer la sécurité de nos rues. 

La violence conjugale 
Que faire lorsque vous êtes dans une relation qui devient violente ? Les personnes victimes de violence conjugale peuvent avoir besoin que quelqu’un intervienne, d’un endroit sûr où aller, de s’éloigner d’un proche et d’un soutien émotionnel. Appeler la police veut dire rajouter de la violence dans une situation où elles y sont déjà confrontées. Les agents de police peuvent mettre la vie d’un proche en danger, ainsi que la leur. Ils sont également deux à quatre fois plus susceptibles de commettre des violences conjugales que les autres membres de la communauté, ce qui en fait un mauvais choix pour les survivant·es qui cherchent de l’aide. 
Minneapolis dispose d’un certain nombre de ressources pour les personnes victimes de violence intra-familiale, notamment contre le harcèlement, les violences verbales, émotionnelles et physiques. La Tubman Crisis Line, Crisis Connection, le Sexual Violence Center, Cornerstone, MN Day One Crisis Hotline, OutFront et Advocare disposent de lignes d'assistance téléphonique en cas de crise. Le Domestic Abuse Project dispose d’une ligne d’urgence pendant les heures d’ouverture en semaine, de conseils individuels et de groupes pour les adultes et les enfants victimes de préjudices, ainsi que d’un soutien pour les adultes qui en ont commis et qui s’efforcent de mettre fin à ce cycle. Crisis Connection, dans les comtés de Washington et d’Anoka, crée des équipes mobiles qui répondent aux appels de détresse lorsque cela est approprié. Les personnes victimes de violence familiale doivent assurer leur sécurité personnelle et celle des autres membres de la famille touchés par la violence. Il est nécessaire de disposer de membres de la communauté en qui on a confiance pour répondre aux situations de violence. Les personnes qui interviennent doivent être capables de lire la situation et être prêtes à intervenir, à désamorcer la situation ou à offrir un soutien émotionnel et un accès à des ressources telles qu’un logement temporaire. Les personnes qui interviennent doivent donner la priorité à la personne qui subit la violence et offrir un soutien à la personne qui la commet. Les agresseurs doivent être tenus responsables, la priorité doit être donnée aux besoins des victimes, tout en suivant les normes déterminées par la communauté et en créant un chemin vers la guérison et la récon­ciliation pour la personne qui a commis le préjudice.
 
La violence sexuelle
Toute violence enfreint les limites des personnes, mais la violence sexuelle peut être particulièrement odieuse en raison de la combinaison des limites physiques, émotionnelles et sexuelles qu’elle franchit. Comme dans le cas de la violence intra-familiale, les policiers ne répondent pas bien aux violences sexuelles pour plusieurs raisons, notamment parce que ceux-ci en commettent plus souvent que le reste de la population. 
Crisis Connection, RAINN, le Sexual Violence Center, MN Day One Crisis Hotline et la National Sexual Assault Telephone Hotline fournissent des lignes d’urgence et un accès à des ressources. Le programme Stop It Now! Helpline est destiné aux adultes qui risquent d’abuser sexuellement d’un enfant, aux proches des survivant·es d’agressions sexuelles et aux parents d’enfants ayant des problèmes de comportement sexuel. 
En plus de ce que nous avons présenté comme des réponses nécessaires aux situations de violence familiale, les sur­vivant·es d’agressions sexuelles peuvent avoir besoin d’un soutien physique et émotionnel spécialisé. Il est de notre responsabilité, en tant que communauté, de nous assurer d’avoir des personnes qui peuvent fournir ce soutien. Nous avons également besoin de membres de la communauté prêts à s’engager auprès de la personne qui a commis l’agression sexuelle, à la tenir responsable de ses actes et à s’attaquer aux causes et aux questions sous-jacentes qui ont pu conduire à ses actes. Nous devons donner la priorité aux besoins des personnes agréssées et établir et suivre des normes communautaires [community norms] pour répondre à la violence sexuelle. VVous trouverez une multitude d’écrits sur les approches abolitionnistes de la prévention de la violence sexuelle sur notre site et sur le centre de ressources TransformHarm.org. 

Le trafic d’être humains et l’exploitation sexuelle 
Là où il y a un traumatisme historique, de la pauvreté et de la marginalisation économique, il y aura toujours une possibi­lité d’exploitation. Le trafic d’être humains et l’exploitation sexuelle, comme d’autres formes d’exploitation de la main-d’œuvre, s’attaquent aux personnes vulnérables, celles dont le pouvoir et l’autonomie ont été confisqués par un système qui les maintient dans un cycle de pénurie, en particulier les femmes et les personnes trans issues des communautés autochtones et des communautés de couleur. 
Certaines ressources sont désormais disponibles pour les survivant·es de la traite : entre autres, TeenPRIDE/The Family Partnership s’occupe des jeunes femmes et des jeunes trans qui ont survécu à la traite humaine et à l’exploitation sexuelle. La Minnesota Indian Women’s Sexual Assault Coalition (MIWSAC) et le Minnesota Indian Women’s Resource Center (MIWRC) œuvrent tous deux spécifiquement au sein des communautés indigènes, en fournissant des services directs et en défendant les intérêts des communautés. Ce ne sont là que quelques organisations parmi tant d'autres qui font ce travail, sans parler des innombrables personnes qui ont consacré leur temps et leur travail à soutenir les victimes-survivantes et à mettre fin à la traite des êtres humains à des fins sexuelles. Au niveau de l'État, le Minnesota a adopté une politique "No Wrong Doors" (pas de mauvaises portes) et est devenu un État "Safe Harbors" en 2014 (pour plus d'informations, veuillez contacter le ministère de la santé du Minnesota). Ces programmes fonctionnent dans une optique spécifique de réponse aux crises et ont leurs propres lacunes, mais ils constituent un début. Bien que tous les programmes et les efforts de réponse continuent d'évoluer, les ressources sont toujours insuffisantes, en particulier pour les adultes et les familles, et les communautés marginalisées sont toujours sur-ciblées par de multiples acteurs et systèmes.
Si nous voulons vraiment soutenir les personnes survivant·es, nous devons investir dans la prévention, et plus particulièrement nous attaquer aux conditions économiques et sociales à l’origine de ces vulnérabilités profondément enracinées.

La consommation de drogues 
La guerre contre la drogue a été très efficace pour criminaliser systématiquement les communautés de personnes de couleur, enfermer des millions de personnes et faire gagner des milliards de dollars à des entreprises carcérales privées. Mais elle a été totalement inefficace pour réduire la disponibilité des drogues ou empêcher les dommages qui peuvent résulter de la consommation de certaines d’entre elles. Tout comme le département de police de Minneapolis n’a pas réussi à arrêter la consommation d’alcool pendant la prohibition dans les années vingt, il n’a pas réussi à réglementer la vente et la consommation d’autres drogues dans les décennies qui ont suivi. 
Malgré une perpétuelle criminalisation de la consommation de drogue, il existe de nombreuses ressources disponibles à Minnea­polis pour aider les utilisateurs, notamment des conseils, l’accès aux seringues, le dépistage du VIH et la prévention des overdoses. Parmi les organisations et les collectifs qui font ce travail, on peut citer HAND, ou Heroin Alternative Needle Distribution, le Minnesota AIDS project, la Minnesota Transgender Health Coalition et le Morpheus Project. 
Il existe une solution simple face à la consommation de drogue dans un monde sans police : la légaliser. Partout aux États-Unis, des communautés ont décriminalisé l’usage récréatif de la marijuana, empêchant ainsi des milliers de membres de la communauté d’être incarcérés pour avoir consommé une drogue relativement inoffensive. D’autres pays sont allés encore plus loin : le Portugal a décriminalisé toutes les drogues en 2000, et a constaté une baisse des infections par le VIH, des décès par overdose et de la consommation générale de drogues. Bien entendu, la décriminalisation ne suffira pas à elle seule à réparer les dommages que la guerre contre la drogue a causés aux communautés de couleur, et toute discussion sur la légalisation devrait inclure la question des dédommagements à accorder aux communautés qui ont été ciblées sous couvert de lutte contre la drogue.

Le travail du sexe 
Bien qu’elle existe à Minneapolis depuis ses débuts, la prostitution est stigmatisée et criminalisée dans notre ville. Le MPD a une longue histoire d’extorsion et d’intimidation des travailleurs et travailleuses du sexe, y compris des cas où des policiers ont menti à des prostituées pour recevoir des faveurs sexuelles avant de les arrêter. MPD150 a contacté le Sex Workers Outreach Project Minneapolis (SWOP MPLS) pour obtenir des informations sur les alternatives existantes face au harcèlement et à la criminalisation par la police. Voici ce qu’ils et elles nous ont envoyé : 
Les ressources qui servent directement la communauté des travailleur·euses du sexe viennent principalement des institutions religieuses qui travaillent en collaboration avec les forces de l’ordre, l’ICE et le mouvement de lutte contre la traite des êtres humains. Certaines organisations opèrent en mode « sauveur » et traitent tout le travail du sexe comme s’il s’agissait d’un trafic. 
En terme de ressources sans jugement pour les travailleur·euses du sexe, nous devons surtout nous tourner vers les communautés pour les droits reproductifs et les ressources pour les homosexuels. Des organisations comme Family Tree Clinic, Aliveness Project, Whole Woman’s Health, Red Door Clinic et Planned Parenthood comprennent l’effet de la stigmatisation sur les travailleur·euses du sexe et offrent des espaces sûrs pour les soins médicaux et le soutien politique. L'Exchange, la Midwest Transgender Health Coalition et le défunt MotherShip ont apporté un soutien pratique à la fondation du Sex Workers Outreach Project MPLS.Le SWOP MPLS est la première organisation constituée de pairs qui défend les droits des travailleur·euses du sexe dans cette ville. Nous avons recueilli sur notre site web des informations sur des thérapeutes, des avocats et des prestataires de services bien informés et sensibles aux besoins des travailleuses du sexe. Malheureusement, cette liste n’est pas très fournie. 
La décriminalisation du travail du sexe est l’objectif central de notre mouvement. La légalisation s’accompagne de réglementations gouvernementales qui causeront des préjudices nouveaux et différents aux travailleur·euses du sexe. Le mode de fonctionnement des maisons closes légales du Nevada et des Pays-Bas s’est avéré quelque peu problématique, et les travailleur·euses hors de ces institutions restent plus exposé·es aux sanctions légales. 
Bien entendu, le fait de rester en dehors de la légalisation nous prive du statut d'employé. Même dans le cadre du travail sexuel actuellement légal, les travailleuses sont considérées comme des entrepreneurs indépendantes. Les outils traditionnels de négociation collective ne sont pas accessibles aux travailleuses du sexe. Nous essayons d'envisager une forme de syndicalisation indépendante, où nous pourrions utiliser nos ressources collectives pour nous fournir en matière d'assurance, de garde d'enfants et, bien sûr, de mesures de sécurité. En général, le mouvement pour les droits des travailleuses du sexe préfère renforcer le statut d'entrepreneur indépendant plutôt que de préconiser de devenir des employés.
Il existe actuellement peu de recours, légaux ou autres, pour les travailleur·euses du sexe. Nous disposons de forums et autres espaces communautaires en ligne où nous pouvons nous signaler les unes aux autres les clients abusifs. Le forum le plus important et le plus efficace est celui de Backpage.com, dont la section « Divertissement pour adultes » a été fermée l’hiver dernier. Quelque chose d’autre apparaîtra à sa place car nous sommes très résilient·es, mais nous avons besoin de meilleurs outils. Les travailleurs et les travailleuses du sexe ont plutôt tendance à faire les choses par elles et eux-mêmes [DIY attitude], et entretiennent une relation compliquée avec le capitalisme. La plupart ne sont pas des révolutionnaires, mais la communauté préférerait être autorisée à s’occuper elle-même de ses problèmes.  

Les atteintes à la propriété 
La plupart des atteintes à la propriété ne sont pas motivées par la malveillance, mais par le désespoir. Une économie capitaliste oblige chacun d’entre nous à se débrouiller seul avec peu de soutien ou d’aide sociale. À une époque où les inégalités de revenus sont historiquement élevées, il n’est pas surprenant que certaines personnes se tournent vers le vol, le cambriolage et d’autres crimes contre la propriété pour subvenir à leurs besoins. La meilleure façon de réduire les délits contre les biens n’est pas d’emprisonner tous les pauvres ou d’essayer d’effrayer les membres de la communauté pour qu’ils obéissent : il s’agit d’investir dès le départ dans les communautés afin que les gens aient moins besoin de se voler les uns les autres. 
En cas de délit contre la propriété, les processus de justice réparatrice et transformatrice donnent souvent de meilleurs résultats que l’arrestation et l’incarcération. Outre les communautés autochtones qui pratiquent des formes holistiques de justice au Minnesota depuis des millénaires, nous avons un certain nombre d’associations qui travaillent dans le domaine de la justice réparatrice à Minneapolis, notamment Restorative Justice Community Action (Action communautaire en matière de justice réparatrice) et Seward Longfellow Restorative Justice Partnership (Partenariat de justice réparatrice de Seward Longfellow).  Actuellement, ces organismes travaillent en étroite collaboration avec le service de police de Minneapolis et le système judiciaire du comté de Hennepin, ce qui permet d'apporter des réponses alternatives à l'incarcération pour des délits mineurs tels que le vol à l'étalage, le vol et la miction publique.

Il n'y a cependant aucune raison que les groupes de justice réparatrice et transformatrice ne puissent pas se suffire à eux-mêmes, en aidant à résoudre de manière proactive les conflits au sein de la communauté sans impliquer le système de justice pénale. Si nous voulons réduire les infractions contre les biens et aider à guérir les auteurs et les victimes, nous devons nous tourner vers la justice réparatrice plutôt que vers l'action policière.

Répondre à la violence 
Nous ne pouvons pas discuter de la manière de répondre à la violence dans nos communautés sans reconnaître que la police la provoque, directement par les coups et les tirs, et indirectement par le harcèlement et la criminalisation. 
Si nous voulons mettre fin à cette violence, il est nécessaire de mettre fin à la violence policière. La police n’est certainement pas la seule source de violence dans notre ville. La violence interpersonnelle a été une constante tout au long de l’histoire de l’humanité, et elle n’est qu’exacerbée par la pauvreté et le désespoir. 
La police n’est pas si efficace que ça pour empêcher la violence. Des études montrent que l’augmentation ou la diminution du nombre de policiers dans une ville n’affecte pas le niveau de criminalité violente, et de nombreuses agressions et de nombreux meurtres ne sont pas résolus. 
Ce qui s’est avéré efficace, ce sont les programmes qui re­donnent des ressources à la communauté, en nous donnant les moyens de prendre nos propres décisions sur la manière de maintenir la sécurité dans nos quartiers. Dans les villes jumelles, les efforts de la communauté pour empêcher la violence comprennent les MAD DADs, le Youth Coordinating Board’s Outreach Team et un certain nombre d’initiatives de prévention de la violence gérées par le département de la santé de la ville. 
Des modèles provenant d’autres régions du pays et du monde peuvent également servir d’inspiration. Les programmes d’interruption de la violence de l’organisation Cure Violence sont un exemple dont l’efficacité à réduire la violence est empiriquement prouvée. Minneapolis commence à investir dans des programmes de sécurité menés par la communauté, mais nous avons encore beaucoup de chemin à parcourir si nous voulons vivre dans une communauté qui traite la violence de manière proactive et humaine.
Répondre à la violence est l’un des défis les plus difficiles auxquels nous sommes confrontés en tant que ville, avec ou sans police. Mais en fournissant des ressources indis­pensables aux différentes communautés, en leur donnant l’espace nécessaire pour créer leurs propres stratégies de sécurité et en rédui­sant notre dépendance à l’égard des réponses inefficaces et nuisibles préconisées par le service de police de Minneapolis, nous pouvons créer une Minneapolis plus sûre et plus saine.

</div>
              
            </Layout>
        </div>
    )
}


export default PartirDesRessourcesExistantes